apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: autoshift-policy-report
spec: {}

---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: autoshift-policy-report

spec:
  source:
    type: Git
    git:
      uri: https://github.com/cziesman/autoshift-policy-report.git
      ref: main
#    sourceSecret:
#      name: autoshift-policy-report

  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: registry.redhat.io/ubi9/openjdk-17:1.24
      pullSecret:
        name: registry-redhat-io

  output:
    to:
      kind: ImageStreamTag
      name: autoshift-policy-report:latest

  triggers:
    - type: ConfigChange