apiVersion: v1
kind: Secret
metadata:
  name: autoshift-policy-report-repository-credentials
type: Opaque
stringData:
  # GitHub PAT or other HTTP(S) Git access token.
  policies-token: REPLACE_ME
  site-values-token: REPLACE_ME
